export const ERROR_CODES = {
  // Authentication & Authorization
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Validation
  INVALID_INPUT: "INVALID_INPUT",

  // Events
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_FULL: "EVENT_FULL",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
